output="./www/"
stylesconfig="styles.toml"

[contact]
name = "Chris Hughes"
email = "chris@chris-hughes.dev"
git = "https://github.com/naokotani"
linkedin = "https://www.linkedin.com/in/chris-hughes-a06867235/"

[about]
image = "pfp.jpg"
html = "./ui/html/pages/about.html"

[site]
meta = "A Developer blog for Chris Hughes. Specializes in JavaScript, Rust, Web development, SQL"
title = "Chris Hughes dot Dev"
subheader="Web development - Database Administration - DevOps"
skilltags="Java | TypeScript | React | Docker | PostgreSQL | AWS | Emacs"

[resume]
html="./ui/html/pages/resume.html"
pdf="chris_hughes_resume.pdf"
