# The location of this config can be changed by setting the eviroment varaible CONFIG_PATH
# to the an absolute path to a config.toml in this format.
#
#Absolute path to output directory. Defaults to ~/Documents/go-emacs/static
output="/home/naokotani/code/go/go-emacs/www"
#Absolute path to styles.toml file. Defaults to ~/Documents/go-emacs/styles.toml
stylesconfig="/home/naokotani/code/go/go-emacs/styles.toml"
#Absolute path to styles.toml file. Defaults to ~/Documents/go-emacs/styles.toml
templateDir="/home/naokotani/code/go/go-emacs/ui"
#Absolute path to styles.toml file. Defaults to ~/Documents/go-emacs/styles.toml
staticDir="/home/naokotani/code/go/go-emacs/static"

# The name should be filled in, but the others can be left blank to remove
[contact]
name = "Joe Dev"
email = "joe@oregon.io"
git = "https://github.com/joedev"
linkedin = "https://www.linkedin.com/in/joe-dev-123456/"

[pages]
#Absolute path to pages directory. Defaults to ~/Documents/go-emacs/pages
dir = "/home/naokotani/code/go/go-emacs/pages"

[posts]
#Absolute path to post directory. Defaults to ~/Documents/go-emacs/posts
dir = "/home/naokotani/code/go/go-emacs/posts"

[resume]
# Set to true to include a resume page with a "download pdf" link.
isResume=true
#Absolute path to resume directory. Defaults to ~/Documents/go-emacs/resume
dir="/home/naokotani/code/go/go-emacs/resume"
# Leave blank for no resume pdf, add the filename of the resume found in the resume folder
pdf=""

[site]
# This will be the meta tag for the website.
meta = "A developer blog sharing insights on full-stack web development, API design, cloud infrastructure, and modern programming languages."
# This will be the title for the Nav and the <title> for the home page.
title = "Joe Dev Zone"
#Sub header on the home page. Leave blank to remove
subheader="Web development - Stuff - DevOps"
#Set to true for card with thumbnail style, false for a list style
cards=true
#This can be any string and will appear below the sub header. Leave blank to remove
skilltags="Haskell | C# | Angular | Docker | MongoDB | AWS | VScode"
# Set to false to skip generation of rss
rss=true
# Site public URL. Used for Rss. If rss=false, no need to set this.
url="https://chris-huhges.dev/"
